# Generated by Django 5.2.1 on 2025-05-26 13:38

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=api.models.PreserveWhitespaceTextField(blank=True, null=True),
        ),
    ]
